name: Universal Mod Core CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                java-version: '1.8' # The JDK version to make available on the path.
                java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
                architecture: x64 # (x64 or x86) - defaults to x64
            - name: keyscan
              run: mkdir -p ~/.ssh/ && ssh-keyscan -t rsa teamopenindustry.cc >> ~/.ssh/known_hosts
            - name: secrets
              env:
                MAVENCI: ${{ secrets.MAVENCI }}
                INIT: |
                  allprojects {
                  buildscript {
                  repositories {
                  maven { url = "https://teamopenindustry.cc/maven" }
                  maven { url "https://repo1.maven.org/maven2/" }
                  }
                  }
                  repositories {
                  maven { url = "https://teamopenindustry.cc/maven" }
                  maven { url "https://repo1.maven.org/maven2/" }
                  }
                  configurations { deployJars }
                  dependencies {
                  deployJars "org.apache.maven.wagon:wagon-ssh:2.9"
                  }
                  ext {
                  filesmaven = {}
                  }
                  filesmaven.url = uri("scp://teamopenindustry.cc/var/www/html/maven/")
                  filesmaven.username = "mavenci"
                  filesmaven.key = "publish_key"
                  }
              run: echo "${MAVENCI}" > publish_key && echo "${INIT}" > init.gradle
            - name: Gradle uploadArchives
              run: ./gradlew --init-script init.gradle uploadArchives
            - name: cleanup
              run: rm publish_key
